name: finsight
description: A comprehensive personal finance management app for students with AI-powered insights and offline-first architecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Local Storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # Charts and Visualization
  fl_chart: ^0.64.0
  
  # HTTP and API
  http: ^1.1.0
  dio: ^5.3.2
  
  # UI and Navigation
  go_router: ^12.1.1
  flutter_screenutil: ^5.9.0
  animations: ^2.0.8
  
  # Security
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  
  # PDF and File Handling
  pdf: ^3.10.7
  open_file: ^3.3.2
  
  # Date and Time
  intl: ^0.19.0
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Voice Input (optional)
  speech_to_text: ^6.6.0
  
  # Image Handling
  image_picker: ^1.0.4
  
  # Notifications
  flutter_local_notifications: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/data/
    - assets/tips.json
    - assets/articles/
    - assets/videos/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
